### ISSUE TITLE
Debe ser tal cosa

### ISSUE THREAD

**Issue by EvelynZapata20** [EvelynZapata20/P1_Project#1]

**Comment by EvelynZapata20** [comment]
**Tasks:**

- [ ] Create the html and css files for each tab.
- [ ] The files must contain the tab bar with its respective redirection to the other files and sections that include a dashboard with the information specified in the requirement.
- [ ] Connect the files of the "pet profile" and "specific appointments" tab, to the "dog" and "appointment" table of the database respectively.
- [ ] Group database records by user.
